# Generated by Django 4.2.14 on 2024-07-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sabad',
            table='sabad',
        ),
    ]
