# Generated by Django 4.2.14 on 2024-07-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_sabad_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabad',
            old_name='title',
            new_name='name',
        ),
    ]
